# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/account_type.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/account_type.proto*\xc7\x01\n\x0b\x41\x63\x63ountType\x12\x18\n\x14\x41\x43\x43OUNT_TYPE_UNKNOWN\x10\x00\x12\x15\n\x11\x41\x43\x43OUNT_TYPE_CASH\x10\x01\x12\x15\n\x11\x41\x43\x43OUNT_TYPE_CARD\x10\x02\x12\x1b\n\x17\x41\x43\x43OUNT_TYPE_ELECTRONIC\x10\x03\x12#\n\x1f\x41\x43\x43OUNT_TYPE_BLOCKCHAIN_ADDRESS\x10\x04\x12\x17\n\x13\x41\x43\x43OUNT_TYPE_EMONEY\x10\x05\x12\x15\n\x11\x41\x43\x43OUNT_TYPE_BANK\x10\x06\x42&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.account_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_ACCOUNTTYPE']._serialized_start=29
  _globals['_ACCOUNTTYPE']._serialized_end=228
# @@protoc_insertion_point(module_scope)
