# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/account_balance.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/account_balance.proto\"\x9c\x02\n\x0e\x41\x63\x63ountBalance\x12\x12\n\naccount_id\x18\x01 \x01(\x05\x12\x17\n\x0freceipts_amount\x18\x02 \x01(\x01\x12\"\n\x1aunverified_receipts_amount\x18\x03 \x01(\x01\x12\x16\n\x0epayouts_amount\x18\x04 \x01(\x01\x12!\n\x19unverified_payouts_amount\x18\x05 \x01(\x01\x12\x0f\n\x07\x62\x61lance\x18\x0b \x01(\x01\x12\x1a\n\x12unverified_balance\x18\x0c \x01(\x01\x12\x15\n\rresource_name\x18\x08 \x01(\tJ\x04\x08\x06\x10\x07J\x04\x08\x07\x10\x08J\x04\x08\n\x10\x0bR\x0eincomes_amountR\x0f\x65xpenses_amountR\x07\x61\x63\x63ountB&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.account_balance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_ACCOUNTBALANCE']._serialized_start=32
  _globals['_ACCOUNTBALANCE']._serialized_end=316
# @@protoc_insertion_point(module_scope)
