# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/account_audit.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from dictum_proto.proto import account_pb2 as proto_dot_account__pb2
from dictum_proto.proto import user_pb2 as proto_dot_user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/account_audit.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13proto/account.proto\x1a\x10proto/user.proto\"\xf6\x02\n\x0c\x41\x63\x63ountAudit\x12\x12\n\naccount_id\x18\x01 \x01(\x05\x12\x10\n\x08\x61udit_id\x18\x02 \x01(\x05\x12\x12\n\nauditor_id\x18\x05 \x01(\x05\x12\x17\n\x0f\x63urrent_balance\x18\x06 \x01(\x01\x12\x15\n\rresource_name\x18\x07 \x01(\t\x12\x1a\n\x12unverified_balance\x18\x08 \x01(\x01\x12\x19\n\x07\x61\x63\x63ount\x18\t \x01(\x0b\x32\x08.Account\x12\x14\n\x0c\x62\x61nk_balance\x18\n \x01(\x01\x12\x17\n\x0f\x62\x61lance_correct\x18\r \x01(\x08\x12/\n\x0b\x63reate_time\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x07\x61uditor\x18\x0f \x01(\x0b\x32\x05.UserJ\x04\x08\x0c\x10\rJ\x04\x08\x0b\x10\x0cJ\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05R\naudit_timeR\x08\x65mployeeR\x0e\x61\x63tual_balanceR\x0f\x61\x63\x63ount_balanceB&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.account_audit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_ACCOUNTAUDIT']._serialized_start=102
  _globals['_ACCOUNTAUDIT']._serialized_end=476
# @@protoc_insertion_point(module_scope)
