# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/accrual_mirror.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dictum_proto.proto import accrual_pb2 as proto_dot_accrual__pb2
from dictum_proto.proto import accrual_mirror_state_pb2 as proto_dot_accrual__mirror__state__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/accrual_mirror.proto\x1a\x13proto/accrual.proto\x1a proto/accrual_mirror_state.proto\"\xdf\x01\n\rAccrualMirror\x12\x1a\n\x12outcome_accrual_id\x18\x01 \x01(\x05\x12\x19\n\x11income_accrual_id\x18\x02 \x01(\x05\x12\x1f\n\x17\x61\x63\x63rual_mirror_state_id\x18\x03 \x01(\x05\x12!\n\x0foutcome_accrual\x18\x05 \x01(\x0b\x32\x08.Accrual\x12 \n\x0eincome_accrual\x18\x07 \x01(\x0b\x32\x08.Accrual\x12\x31\n\x14\x61\x63\x63rual_mirror_state\x18\t \x01(\x0b\x32\x13.AccrualMirrorStateB&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.accrual_mirror_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_ACCRUALMIRROR']._serialized_start=86
  _globals['_ACCRUALMIRROR']._serialized_end=309
# @@protoc_insertion_point(module_scope)
