# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/accrual_status_transition.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dictum_proto.proto import payment_type_pb2 as proto_dot_payment__type__pb2
from dictum_proto.proto import side_deal_type_pb2 as proto_dot_side__deal__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%proto/accrual_status_transition.proto\x1a\x18proto/payment_type.proto\x1a\x1aproto/side_deal_type.proto\"\x9e\x01\n\x17\x41\x63\x63rualStatusTransition\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0bnext_status\x18\x02 \x01(\t\x12\"\n\x0cpayment_type\x18\x03 \x01(\x0e\x32\x0c.PaymentType\x12\x18\n\x10is_external_flow\x18\x04 \x01(\x08\x12 \n\tside_deal\x18\x05 \x01(\x0e\x32\r.SideDealTypeB&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.accrual_status_transition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_ACCRUALSTATUSTRANSITION']._serialized_start=96
  _globals['_ACCRUALSTATUSTRANSITION']._serialized_end=254
# @@protoc_insertion_point(module_scope)
