# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/action.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dictum_proto.proto import action_type_pb2 as proto_dot_action__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/action.proto\x1a\x17proto/action_type.proto\"v\n\x06\x41\x63tion\x12\x11\n\taction_id\x18\x01 \x01(\x05\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.ActionType\x12\x12\n\nscope_name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x15\n\rresource_name\x18\x05 \x01(\tB&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.action_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_ACTION']._serialized_start=47
  _globals['_ACTION']._serialized_end=165
# @@protoc_insertion_point(module_scope)
