# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/action_type.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/action_type.proto*\xca\x02\n\nActionType\x12\x17\n\x13\x41\x43TION_TYPE_UNKNOWN\x10\x00\x12\x1d\n\x19\x41\x43TION_TYPE_CONFIRM_ENTRY\x10\x01\x12\x15\n\x11\x41\x43TION_TYPE_AUDIT\x10\x02\x12\x1c\n\x18\x41\x43TION_TYPE_ALLOW_PAYOUT\x10\x03\x12\x16\n\x12\x41\x43TION_TYPE_PAYOUT\x10\x04\x12\x19\n\x15\x41\x43TION_TYPE_MARK_PAID\x10\x05\x12\x1f\n\x1b\x41\x43TION_TYPE_DISALLOW_PAYOUT\x10\x06\x12\x1c\n\x18\x41\x43TION_TYPE_CANCEL_AUDIT\x10\x07\x12#\n\x1f\x41\x43TION_TYPE_CANCEL_CONFIRMATION\x10\x08\x12\x16\n\x12\x41\x43TION_TYPE_CANCEL\x10\t\x12 \n\x1c\x41\x43TION_TYPE_CANCEL_MARK_PAID\x10\nB&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.action_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_ACTIONTYPE']._serialized_start=28
  _globals['_ACTIONTYPE']._serialized_end=358
# @@protoc_insertion_point(module_scope)
