# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/attachment.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from dictum_proto.proto import attachment_type_pb2 as proto_dot_attachment__type__pb2
from dictum_proto.proto import user_pb2 as proto_dot_user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/attachment.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bproto/attachment_type.proto\x1a\x10proto/user.proto\"\x83\x02\n\nAttachment\x12\x15\n\rattachment_id\x18\x01 \x01(\x05\x12\x0f\n\x07raw_url\x18\x02 \x01(\t\x12\x11\n\tmime_type\x18\x03 \x01(\t\x12\x1d\n\x04type\x18\x04 \x01(\x0e\x32\x0f.AttachmentType\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x13\n\x0buploader_id\x18\x06 \x01(\x05\x12\x15\n\rresource_name\x18\x07 \x01(\t\x12/\n\x0b\x63reate_time\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x08uploader\x18\t \x01(\x0b\x32\x05.User\x12\x17\n\x0f\x65xternal_number\x18\n \x01(\tB&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.attachment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_ATTACHMENT']._serialized_start=107
  _globals['_ATTACHMENT']._serialized_end=366
# @@protoc_insertion_point(module_scope)
