# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/direction.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/direction.proto*{\n\tDirection\x12\x15\n\x11\x44IRECTION_UNKNOWN\x10\x00\x12\x14\n\x10\x44IRECTION_INCOME\x10\x01\x12\x15\n\x11\x44IRECTION_OUTCOME\x10\x04\x12\x11\n\rDIRECTION_ANY\x10\x03\"\x04\x08\x02\x10\x02*\x11\x44IRECTION_EXPENSEB&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.direction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_DIRECTION']._serialized_start=25
  _globals['_DIRECTION']._serialized_end=148
# @@protoc_insertion_point(module_scope)
