# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from dictum_proto.proto import account_audit_pb2 as proto_dot_account__audit__pb2
from dictum_proto.proto import account_balance_pb2 as proto_dot_account__balance__pb2
from dictum_proto.proto import account_detail_pb2 as proto_dot_account__detail__pb2
from dictum_proto.proto import account_pb2 as proto_dot_account__pb2
from dictum_proto.proto import employee_pb2 as proto_dot_employee__pb2
from dictum_proto.proto import entity_aggregate_pb2 as proto_dot_entity__aggregate__pb2
from dictum_proto.proto import entity_hub_pb2 as proto_dot_entity__hub__pb2
from dictum_proto.proto import entity_pb2 as proto_dot_entity__pb2
from dictum_proto.proto import requests_pb2 as proto_dot_requests__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/entity_hub_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class EntityHubStub(object):
    """Репо - Entity, Account
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListEntities = channel.unary_unary(
                '/EntityHub/ListEntities',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_entity__hub__pb2.ListEntitiesResponse.FromString,
                _registered_method=True)
        self.GetEntity = channel.unary_unary(
                '/EntityHub/GetEntity',
                request_serializer=proto_dot_requests__pb2.GetRequest.SerializeToString,
                response_deserializer=proto_dot_entity__pb2.Entity.FromString,
                _registered_method=True)
        self.CreateEntity = channel.unary_unary(
                '/EntityHub/CreateEntity',
                request_serializer=proto_dot_entity__pb2.Entity.SerializeToString,
                response_deserializer=proto_dot_entity__pb2.Entity.FromString,
                _registered_method=True)
        self.BatchInsertEntities = channel.unary_unary(
                '/EntityHub/BatchInsertEntities',
                request_serializer=proto_dot_entity__hub__pb2.BatchInsertEntitiesRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateEntity = channel.unary_unary(
                '/EntityHub/UpdateEntity',
                request_serializer=proto_dot_entity__pb2.Entity.SerializeToString,
                response_deserializer=proto_dot_entity__pb2.Entity.FromString,
                _registered_method=True)
        self.AggregateEntity = channel.unary_unary(
                '/EntityHub/AggregateEntity',
                request_serializer=proto_dot_requests__pb2.GetRequest.SerializeToString,
                response_deserializer=proto_dot_entity__aggregate__pb2.EntityAggregate.FromString,
                _registered_method=True)
        self.ListEmployees = channel.unary_unary(
                '/EntityHub/ListEmployees',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_entity__hub__pb2.ListEmployeesResponse.FromString,
                _registered_method=True)
        self.GetEmployee = channel.unary_unary(
                '/EntityHub/GetEmployee',
                request_serializer=proto_dot_requests__pb2.GetRequest.SerializeToString,
                response_deserializer=proto_dot_employee__pb2.Employee.FromString,
                _registered_method=True)
        self.CreateEmployee = channel.unary_unary(
                '/EntityHub/CreateEmployee',
                request_serializer=proto_dot_employee__pb2.Employee.SerializeToString,
                response_deserializer=proto_dot_employee__pb2.Employee.FromString,
                _registered_method=True)
        self.DeleteEmployee = channel.unary_unary(
                '/EntityHub/DeleteEmployee',
                request_serializer=proto_dot_requests__pb2.DeleteRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListCountries = channel.unary_unary(
                '/EntityHub/ListCountries',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_entity__hub__pb2.ListCountriesResponse.FromString,
                _registered_method=True)
        self.ListAccounts = channel.unary_unary(
                '/EntityHub/ListAccounts',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_entity__hub__pb2.ListAccountsResponse.FromString,
                _registered_method=True)
        self.ListAccountDetails = channel.unary_unary(
                '/EntityHub/ListAccountDetails',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_entity__hub__pb2.ListAccountDetailsResponse.FromString,
                _registered_method=True)
        self.GetAccount = channel.unary_unary(
                '/EntityHub/GetAccount',
                request_serializer=proto_dot_requests__pb2.GetRequest.SerializeToString,
                response_deserializer=proto_dot_account__pb2.Account.FromString,
                _registered_method=True)
        self.GetAccountDetail = channel.unary_unary(
                '/EntityHub/GetAccountDetail',
                request_serializer=proto_dot_requests__pb2.GetRequest.SerializeToString,
                response_deserializer=proto_dot_account__detail__pb2.AccountDetail.FromString,
                _registered_method=True)
        self.CreateAccount = channel.unary_unary(
                '/EntityHub/CreateAccount',
                request_serializer=proto_dot_account__pb2.Account.SerializeToString,
                response_deserializer=proto_dot_account__pb2.Account.FromString,
                _registered_method=True)
        self.CreateAccountDetails = channel.unary_unary(
                '/EntityHub/CreateAccountDetails',
                request_serializer=proto_dot_account__detail__pb2.AccountDetail.SerializeToString,
                response_deserializer=proto_dot_account__detail__pb2.AccountDetail.FromString,
                _registered_method=True)
        self.BatchInsertAccounts = channel.unary_unary(
                '/EntityHub/BatchInsertAccounts',
                request_serializer=proto_dot_entity__hub__pb2.BatchInsertAccountsRequest.SerializeToString,
                response_deserializer=proto_dot_entity__hub__pb2.BatchInsertAccountsResponse.FromString,
                _registered_method=True)
        self.UpdateAccount = channel.unary_unary(
                '/EntityHub/UpdateAccount',
                request_serializer=proto_dot_account__pb2.Account.SerializeToString,
                response_deserializer=proto_dot_account__pb2.Account.FromString,
                _registered_method=True)
        self.UpdateAccountDetails = channel.unary_unary(
                '/EntityHub/UpdateAccountDetails',
                request_serializer=proto_dot_account__detail__pb2.AccountDetail.SerializeToString,
                response_deserializer=proto_dot_account__detail__pb2.AccountDetail.FromString,
                _registered_method=True)
        self.DeleteAccount = channel.unary_unary(
                '/EntityHub/DeleteAccount',
                request_serializer=proto_dot_requests__pb2.DeleteRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListCurrencies = channel.unary_unary(
                '/EntityHub/ListCurrencies',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_entity__hub__pb2.ListCurrenciesResponse.FromString,
                _registered_method=True)
        self.ListActualCurrencyRates = channel.unary_unary(
                '/EntityHub/ListActualCurrencyRates',
                request_serializer=proto_dot_entity__hub__pb2.ListActualCurrencyRatesRequest.SerializeToString,
                response_deserializer=proto_dot_entity__hub__pb2.ListActualCurrencyRatesResponse.FromString,
                _registered_method=True)
        self.BatchInsertCurrencyRates = channel.unary_unary(
                '/EntityHub/BatchInsertCurrencyRates',
                request_serializer=proto_dot_entity__hub__pb2.BatchInsertCurrencyRatesRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListFis = channel.unary_unary(
                '/EntityHub/ListFis',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_entity__hub__pb2.ListFisResponse.FromString,
                _registered_method=True)
        self.ListAccountAudits = channel.unary_unary(
                '/EntityHub/ListAccountAudits',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_entity__hub__pb2.ListAccountAuditsResponse.FromString,
                _registered_method=True)
        self.GetAccountAudit = channel.unary_unary(
                '/EntityHub/GetAccountAudit',
                request_serializer=proto_dot_requests__pb2.GetRequest.SerializeToString,
                response_deserializer=proto_dot_account__audit__pb2.AccountAudit.FromString,
                _registered_method=True)
        self.GetAccountBalance = channel.unary_unary(
                '/EntityHub/GetAccountBalance',
                request_serializer=proto_dot_requests__pb2.GetRequest.SerializeToString,
                response_deserializer=proto_dot_account__balance__pb2.AccountBalance.FromString,
                _registered_method=True)
        self.CreateAccountAudit = channel.unary_unary(
                '/EntityHub/CreateAccountAudit',
                request_serializer=proto_dot_account__audit__pb2.AccountAudit.SerializeToString,
                response_deserializer=proto_dot_account__audit__pb2.AccountAudit.FromString,
                _registered_method=True)
        self.RequestEmployee = channel.unary_unary(
                '/EntityHub/RequestEmployee',
                request_serializer=proto_dot_entity__hub__pb2.RequestEmployeeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RequestPartnership = channel.unary_unary(
                '/EntityHub/RequestPartnership',
                request_serializer=proto_dot_entity__hub__pb2.RequestPartnershipRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListEntityAccesses = channel.unary_unary(
                '/EntityHub/ListEntityAccesses',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_entity__hub__pb2.ListEntityAccessesResponse.FromString,
                _registered_method=True)
        self.DeleteEntityAccess = channel.unary_unary(
                '/EntityHub/DeleteEntityAccess',
                request_serializer=proto_dot_requests__pb2.DeleteRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class EntityHubServicer(object):
    """Репо - Entity, Account
    """

    def ListEntities(self, request, context):
        """--
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInsertEntities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AggregateEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEmployees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCountries(self, request, context):
        """--
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccounts(self, request, context):
        """--
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccountDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccountDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInsertAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAccountDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCurrencies(self, request, context):
        """--
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActualCurrencyRates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInsertCurrencyRates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFis(self, request, context):
        """--
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccountAudits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountAudit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccountAudit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPartnership(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEntityAccesses(self, request, context):
        """--
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEntityAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EntityHubServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEntities,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_entity__hub__pb2.ListEntitiesResponse.SerializeToString,
            ),
            'GetEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntity,
                    request_deserializer=proto_dot_requests__pb2.GetRequest.FromString,
                    response_serializer=proto_dot_entity__pb2.Entity.SerializeToString,
            ),
            'CreateEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEntity,
                    request_deserializer=proto_dot_entity__pb2.Entity.FromString,
                    response_serializer=proto_dot_entity__pb2.Entity.SerializeToString,
            ),
            'BatchInsertEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchInsertEntities,
                    request_deserializer=proto_dot_entity__hub__pb2.BatchInsertEntitiesRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEntity,
                    request_deserializer=proto_dot_entity__pb2.Entity.FromString,
                    response_serializer=proto_dot_entity__pb2.Entity.SerializeToString,
            ),
            'AggregateEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.AggregateEntity,
                    request_deserializer=proto_dot_requests__pb2.GetRequest.FromString,
                    response_serializer=proto_dot_entity__aggregate__pb2.EntityAggregate.SerializeToString,
            ),
            'ListEmployees': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEmployees,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_entity__hub__pb2.ListEmployeesResponse.SerializeToString,
            ),
            'GetEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmployee,
                    request_deserializer=proto_dot_requests__pb2.GetRequest.FromString,
                    response_serializer=proto_dot_employee__pb2.Employee.SerializeToString,
            ),
            'CreateEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEmployee,
                    request_deserializer=proto_dot_employee__pb2.Employee.FromString,
                    response_serializer=proto_dot_employee__pb2.Employee.SerializeToString,
            ),
            'DeleteEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEmployee,
                    request_deserializer=proto_dot_requests__pb2.DeleteRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListCountries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCountries,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_entity__hub__pb2.ListCountriesResponse.SerializeToString,
            ),
            'ListAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccounts,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_entity__hub__pb2.ListAccountsResponse.SerializeToString,
            ),
            'ListAccountDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccountDetails,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_entity__hub__pb2.ListAccountDetailsResponse.SerializeToString,
            ),
            'GetAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccount,
                    request_deserializer=proto_dot_requests__pb2.GetRequest.FromString,
                    response_serializer=proto_dot_account__pb2.Account.SerializeToString,
            ),
            'GetAccountDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountDetail,
                    request_deserializer=proto_dot_requests__pb2.GetRequest.FromString,
                    response_serializer=proto_dot_account__detail__pb2.AccountDetail.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=proto_dot_account__pb2.Account.FromString,
                    response_serializer=proto_dot_account__pb2.Account.SerializeToString,
            ),
            'CreateAccountDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccountDetails,
                    request_deserializer=proto_dot_account__detail__pb2.AccountDetail.FromString,
                    response_serializer=proto_dot_account__detail__pb2.AccountDetail.SerializeToString,
            ),
            'BatchInsertAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchInsertAccounts,
                    request_deserializer=proto_dot_entity__hub__pb2.BatchInsertAccountsRequest.FromString,
                    response_serializer=proto_dot_entity__hub__pb2.BatchInsertAccountsResponse.SerializeToString,
            ),
            'UpdateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAccount,
                    request_deserializer=proto_dot_account__pb2.Account.FromString,
                    response_serializer=proto_dot_account__pb2.Account.SerializeToString,
            ),
            'UpdateAccountDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAccountDetails,
                    request_deserializer=proto_dot_account__detail__pb2.AccountDetail.FromString,
                    response_serializer=proto_dot_account__detail__pb2.AccountDetail.SerializeToString,
            ),
            'DeleteAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAccount,
                    request_deserializer=proto_dot_requests__pb2.DeleteRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListCurrencies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCurrencies,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_entity__hub__pb2.ListCurrenciesResponse.SerializeToString,
            ),
            'ListActualCurrencyRates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActualCurrencyRates,
                    request_deserializer=proto_dot_entity__hub__pb2.ListActualCurrencyRatesRequest.FromString,
                    response_serializer=proto_dot_entity__hub__pb2.ListActualCurrencyRatesResponse.SerializeToString,
            ),
            'BatchInsertCurrencyRates': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchInsertCurrencyRates,
                    request_deserializer=proto_dot_entity__hub__pb2.BatchInsertCurrencyRatesRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListFis': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFis,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_entity__hub__pb2.ListFisResponse.SerializeToString,
            ),
            'ListAccountAudits': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccountAudits,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_entity__hub__pb2.ListAccountAuditsResponse.SerializeToString,
            ),
            'GetAccountAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountAudit,
                    request_deserializer=proto_dot_requests__pb2.GetRequest.FromString,
                    response_serializer=proto_dot_account__audit__pb2.AccountAudit.SerializeToString,
            ),
            'GetAccountBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountBalance,
                    request_deserializer=proto_dot_requests__pb2.GetRequest.FromString,
                    response_serializer=proto_dot_account__balance__pb2.AccountBalance.SerializeToString,
            ),
            'CreateAccountAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccountAudit,
                    request_deserializer=proto_dot_account__audit__pb2.AccountAudit.FromString,
                    response_serializer=proto_dot_account__audit__pb2.AccountAudit.SerializeToString,
            ),
            'RequestEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestEmployee,
                    request_deserializer=proto_dot_entity__hub__pb2.RequestEmployeeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RequestPartnership': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPartnership,
                    request_deserializer=proto_dot_entity__hub__pb2.RequestPartnershipRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListEntityAccesses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEntityAccesses,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_entity__hub__pb2.ListEntityAccessesResponse.SerializeToString,
            ),
            'DeleteEntityAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEntityAccess,
                    request_deserializer=proto_dot_requests__pb2.DeleteRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EntityHub', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('EntityHub', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EntityHub(object):
    """Репо - Entity, Account
    """

    @staticmethod
    def ListEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/ListEntities',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_entity__hub__pb2.ListEntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/GetEntity',
            proto_dot_requests__pb2.GetRequest.SerializeToString,
            proto_dot_entity__pb2.Entity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/CreateEntity',
            proto_dot_entity__pb2.Entity.SerializeToString,
            proto_dot_entity__pb2.Entity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInsertEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/BatchInsertEntities',
            proto_dot_entity__hub__pb2.BatchInsertEntitiesRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/UpdateEntity',
            proto_dot_entity__pb2.Entity.SerializeToString,
            proto_dot_entity__pb2.Entity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AggregateEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/AggregateEntity',
            proto_dot_requests__pb2.GetRequest.SerializeToString,
            proto_dot_entity__aggregate__pb2.EntityAggregate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEmployees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/ListEmployees',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_entity__hub__pb2.ListEmployeesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/GetEmployee',
            proto_dot_requests__pb2.GetRequest.SerializeToString,
            proto_dot_employee__pb2.Employee.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/CreateEmployee',
            proto_dot_employee__pb2.Employee.SerializeToString,
            proto_dot_employee__pb2.Employee.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/DeleteEmployee',
            proto_dot_requests__pb2.DeleteRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCountries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/ListCountries',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_entity__hub__pb2.ListCountriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/ListAccounts',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_entity__hub__pb2.ListAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAccountDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/ListAccountDetails',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_entity__hub__pb2.ListAccountDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/GetAccount',
            proto_dot_requests__pb2.GetRequest.SerializeToString,
            proto_dot_account__pb2.Account.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/GetAccountDetail',
            proto_dot_requests__pb2.GetRequest.SerializeToString,
            proto_dot_account__detail__pb2.AccountDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/CreateAccount',
            proto_dot_account__pb2.Account.SerializeToString,
            proto_dot_account__pb2.Account.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAccountDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/CreateAccountDetails',
            proto_dot_account__detail__pb2.AccountDetail.SerializeToString,
            proto_dot_account__detail__pb2.AccountDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInsertAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/BatchInsertAccounts',
            proto_dot_entity__hub__pb2.BatchInsertAccountsRequest.SerializeToString,
            proto_dot_entity__hub__pb2.BatchInsertAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/UpdateAccount',
            proto_dot_account__pb2.Account.SerializeToString,
            proto_dot_account__pb2.Account.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAccountDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/UpdateAccountDetails',
            proto_dot_account__detail__pb2.AccountDetail.SerializeToString,
            proto_dot_account__detail__pb2.AccountDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/DeleteAccount',
            proto_dot_requests__pb2.DeleteRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCurrencies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/ListCurrencies',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_entity__hub__pb2.ListCurrenciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActualCurrencyRates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/ListActualCurrencyRates',
            proto_dot_entity__hub__pb2.ListActualCurrencyRatesRequest.SerializeToString,
            proto_dot_entity__hub__pb2.ListActualCurrencyRatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInsertCurrencyRates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/BatchInsertCurrencyRates',
            proto_dot_entity__hub__pb2.BatchInsertCurrencyRatesRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/ListFis',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_entity__hub__pb2.ListFisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAccountAudits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/ListAccountAudits',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_entity__hub__pb2.ListAccountAuditsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/GetAccountAudit',
            proto_dot_requests__pb2.GetRequest.SerializeToString,
            proto_dot_account__audit__pb2.AccountAudit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/GetAccountBalance',
            proto_dot_requests__pb2.GetRequest.SerializeToString,
            proto_dot_account__balance__pb2.AccountBalance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAccountAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/CreateAccountAudit',
            proto_dot_account__audit__pb2.AccountAudit.SerializeToString,
            proto_dot_account__audit__pb2.AccountAudit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/RequestEmployee',
            proto_dot_entity__hub__pb2.RequestEmployeeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestPartnership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/RequestPartnership',
            proto_dot_entity__hub__pb2.RequestPartnershipRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEntityAccesses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/ListEntityAccesses',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_entity__hub__pb2.ListEntityAccessesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEntityAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EntityHub/DeleteEntityAccess',
            proto_dot_requests__pb2.DeleteRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
