# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/entity_role.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from dictum_proto.proto import entity_pb2 as proto_dot_entity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/entity_role.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12proto/entity.proto\"s\n\nEntityRole\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x17\n\x06\x65ntity\x18\x02 \x01(\x0b\x32\x07.Entity\x12\x0c\n\x04role\x18\x03 \x01(\t\x12-\n\thire_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampB&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.entity_role_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_ENTITYROLE']._serialized_start=80
  _globals['_ENTITYROLE']._serialized_end=195
# @@protoc_insertion_point(module_scope)
