# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from dictum_proto.proto import accrual_pb2 as proto_dot_accrual__pb2
from dictum_proto.proto import accruals_aggregate_pb2 as proto_dot_accruals__aggregate__pb2
from dictum_proto.proto import allocation_pb2 as proto_dot_allocation__pb2
from dictum_proto.proto import article_pb2 as proto_dot_article__pb2
from dictum_proto.proto import comment_pb2 as proto_dot_comment__pb2
from dictum_proto.proto import event_aggregate_pb2 as proto_dot_event__aggregate__pb2
from dictum_proto.proto import fin_event_pb2 as proto_dot_fin__event__pb2
from dictum_proto.proto import permission_pb2 as proto_dot_permission__pb2
from dictum_proto.proto import position_pb2 as proto_dot_position__pb2
from dictum_proto.proto import requests_pb2 as proto_dot_requests__pb2
from dictum_proto.proto import transfer_pb2 as proto_dot_transfer__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/fin_event_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class FinEventStub(object):
    """Репы - Трансферы, Перевод, Продукт
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSignatures = channel.unary_unary(
                '/FinEvent/ListSignatures',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_fin__event__pb2.ListSignaturesResponse.FromString,
                _registered_method=True)
        self.ListComments = channel.unary_unary(
                '/FinEvent/ListComments',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_fin__event__pb2.ListCommentsResponse.FromString,
                _registered_method=True)
        self.CreateComment = channel.unary_unary(
                '/FinEvent/CreateComment',
                request_serializer=proto_dot_comment__pb2.Comment.SerializeToString,
                response_deserializer=proto_dot_comment__pb2.Comment.FromString,
                _registered_method=True)
        self.UpdateComment = channel.unary_unary(
                '/FinEvent/UpdateComment',
                request_serializer=proto_dot_comment__pb2.Comment.SerializeToString,
                response_deserializer=proto_dot_comment__pb2.Comment.FromString,
                _registered_method=True)
        self.DeleteComment = channel.unary_unary(
                '/FinEvent/DeleteComment',
                request_serializer=proto_dot_requests__pb2.DeleteRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreatePermission = channel.unary_unary(
                '/FinEvent/CreatePermission',
                request_serializer=proto_dot_permission__pb2.Permission.SerializeToString,
                response_deserializer=proto_dot_permission__pb2.Permission.FromString,
                _registered_method=True)
        self.ListPermissions = channel.unary_unary(
                '/FinEvent/ListPermissions',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_fin__event__pb2.ListPermissionsResponse.FromString,
                _registered_method=True)
        self.DeletePermission = channel.unary_unary(
                '/FinEvent/DeletePermission',
                request_serializer=proto_dot_requests__pb2.DeleteRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListActions = channel.unary_unary(
                '/FinEvent/ListActions',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_fin__event__pb2.ListActionsResponse.FromString,
                _registered_method=True)
        self.ListTransfers = channel.unary_unary(
                '/FinEvent/ListTransfers',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_fin__event__pb2.ListTransfersResponse.FromString,
                _registered_method=True)
        self.GetTransfer = channel.unary_unary(
                '/FinEvent/GetTransfer',
                request_serializer=proto_dot_requests__pb2.GetRequest.SerializeToString,
                response_deserializer=proto_dot_transfer__pb2.Transfer.FromString,
                _registered_method=True)
        self.CreateTransfer = channel.unary_unary(
                '/FinEvent/CreateTransfer',
                request_serializer=proto_dot_transfer__pb2.Transfer.SerializeToString,
                response_deserializer=proto_dot_transfer__pb2.Transfer.FromString,
                _registered_method=True)
        self.AllocateTransfer = channel.unary_unary(
                '/FinEvent/AllocateTransfer',
                request_serializer=proto_dot_fin__event__pb2.AllocateTransferRequest.SerializeToString,
                response_deserializer=proto_dot_allocation__pb2.Allocation.FromString,
                _registered_method=True)
        self.BatchInsertTransfers = channel.unary_unary(
                '/FinEvent/BatchInsertTransfers',
                request_serializer=proto_dot_fin__event__pb2.BatchInsertTransfersRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateTransfer = channel.unary_unary(
                '/FinEvent/UpdateTransfer',
                request_serializer=proto_dot_transfer__pb2.Transfer.SerializeToString,
                response_deserializer=proto_dot_transfer__pb2.Transfer.FromString,
                _registered_method=True)
        self.AggregateTransfers = channel.unary_unary(
                '/FinEvent/AggregateTransfers',
                request_serializer=proto_dot_requests__pb2.AggregateRequest.SerializeToString,
                response_deserializer=proto_dot_event__aggregate__pb2.EventAggregate.FromString,
                _registered_method=True)
        self.ListAccruals = channel.unary_unary(
                '/FinEvent/ListAccruals',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_fin__event__pb2.ListAccrualsResponse.FromString,
                _registered_method=True)
        self.GetAccrual = channel.unary_unary(
                '/FinEvent/GetAccrual',
                request_serializer=proto_dot_requests__pb2.GetRequest.SerializeToString,
                response_deserializer=proto_dot_accrual__pb2.Accrual.FromString,
                _registered_method=True)
        self.CreateAccrual = channel.unary_unary(
                '/FinEvent/CreateAccrual',
                request_serializer=proto_dot_accrual__pb2.Accrual.SerializeToString,
                response_deserializer=proto_dot_accrual__pb2.Accrual.FromString,
                _registered_method=True)
        self.UpdateAccrual = channel.unary_unary(
                '/FinEvent/UpdateAccrual',
                request_serializer=proto_dot_accrual__pb2.Accrual.SerializeToString,
                response_deserializer=proto_dot_accrual__pb2.Accrual.FromString,
                _registered_method=True)
        self.AggregateAccruals = channel.unary_unary(
                '/FinEvent/AggregateAccruals',
                request_serializer=proto_dot_requests__pb2.AggregateRequest.SerializeToString,
                response_deserializer=proto_dot_accruals__aggregate__pb2.AccrualsAggregate.FromString,
                _registered_method=True)
        self.BatchInsertAccruals = channel.unary_unary(
                '/FinEvent/BatchInsertAccruals',
                request_serializer=proto_dot_fin__event__pb2.BatchInsertAccrualsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GenerateAccrualPDF = channel.unary_unary(
                '/FinEvent/GenerateAccrualPDF',
                request_serializer=proto_dot_requests__pb2.GetRequest.SerializeToString,
                response_deserializer=proto_dot_fin__event__pb2.FileResponse.FromString,
                _registered_method=True)
        self.ListProducts = channel.unary_unary(
                '/FinEvent/ListProducts',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_fin__event__pb2.ListProductsResponse.FromString,
                _registered_method=True)
        self.ListPositions = channel.unary_unary(
                '/FinEvent/ListPositions',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_fin__event__pb2.ListPositionsResponse.FromString,
                _registered_method=True)
        self.UpdatePosition = channel.unary_unary(
                '/FinEvent/UpdatePosition',
                request_serializer=proto_dot_position__pb2.Position.SerializeToString,
                response_deserializer=proto_dot_position__pb2.Position.FromString,
                _registered_method=True)
        self.BatchInsertPostions = channel.unary_unary(
                '/FinEvent/BatchInsertPostions',
                request_serializer=proto_dot_fin__event__pb2.BatchInsertPositionsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListArticles = channel.unary_unary(
                '/FinEvent/ListArticles',
                request_serializer=proto_dot_fin__event__pb2.ListArticlesRequest.SerializeToString,
                response_deserializer=proto_dot_fin__event__pb2.ListArticlesResponse.FromString,
                _registered_method=True)
        self.GetArticle = channel.unary_unary(
                '/FinEvent/GetArticle',
                request_serializer=proto_dot_requests__pb2.GetRequest.SerializeToString,
                response_deserializer=proto_dot_article__pb2.Article.FromString,
                _registered_method=True)
        self.CreateArticle = channel.unary_unary(
                '/FinEvent/CreateArticle',
                request_serializer=proto_dot_article__pb2.Article.SerializeToString,
                response_deserializer=proto_dot_article__pb2.Article.FromString,
                _registered_method=True)
        self.UpdateArticle = channel.unary_unary(
                '/FinEvent/UpdateArticle',
                request_serializer=proto_dot_article__pb2.Article.SerializeToString,
                response_deserializer=proto_dot_article__pb2.Article.FromString,
                _registered_method=True)
        self.DeleteArticle = channel.unary_unary(
                '/FinEvent/DeleteArticle',
                request_serializer=proto_dot_requests__pb2.DeleteRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListAllocations = channel.unary_unary(
                '/FinEvent/ListAllocations',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_fin__event__pb2.ListAllocationsResponse.FromString,
                _registered_method=True)
        self.CreateAllocation = channel.unary_unary(
                '/FinEvent/CreateAllocation',
                request_serializer=proto_dot_allocation__pb2.Allocation.SerializeToString,
                response_deserializer=proto_dot_allocation__pb2.Allocation.FromString,
                _registered_method=True)


class FinEventServicer(object):
    """Репы - Трансферы, Перевод, Продукт
    """

    def ListSignatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPermissions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTransfers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllocateTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInsertTransfers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AggregateTransfers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccruals(self, request, context):
        """--
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccrual(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccrual(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAccrual(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AggregateAccruals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInsertAccruals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateAccrualPDF(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProducts(self, request, context):
        """--
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInsertPostions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListArticles(self, request, context):
        """--
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllocations(self, request, context):
        """--
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAllocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FinEventServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSignatures': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSignatures,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_fin__event__pb2.ListSignaturesResponse.SerializeToString,
            ),
            'ListComments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListComments,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_fin__event__pb2.ListCommentsResponse.SerializeToString,
            ),
            'CreateComment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateComment,
                    request_deserializer=proto_dot_comment__pb2.Comment.FromString,
                    response_serializer=proto_dot_comment__pb2.Comment.SerializeToString,
            ),
            'UpdateComment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateComment,
                    request_deserializer=proto_dot_comment__pb2.Comment.FromString,
                    response_serializer=proto_dot_comment__pb2.Comment.SerializeToString,
            ),
            'DeleteComment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteComment,
                    request_deserializer=proto_dot_requests__pb2.DeleteRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreatePermission': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePermission,
                    request_deserializer=proto_dot_permission__pb2.Permission.FromString,
                    response_serializer=proto_dot_permission__pb2.Permission.SerializeToString,
            ),
            'ListPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPermissions,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_fin__event__pb2.ListPermissionsResponse.SerializeToString,
            ),
            'DeletePermission': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePermission,
                    request_deserializer=proto_dot_requests__pb2.DeleteRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListActions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActions,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_fin__event__pb2.ListActionsResponse.SerializeToString,
            ),
            'ListTransfers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTransfers,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_fin__event__pb2.ListTransfersResponse.SerializeToString,
            ),
            'GetTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransfer,
                    request_deserializer=proto_dot_requests__pb2.GetRequest.FromString,
                    response_serializer=proto_dot_transfer__pb2.Transfer.SerializeToString,
            ),
            'CreateTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTransfer,
                    request_deserializer=proto_dot_transfer__pb2.Transfer.FromString,
                    response_serializer=proto_dot_transfer__pb2.Transfer.SerializeToString,
            ),
            'AllocateTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocateTransfer,
                    request_deserializer=proto_dot_fin__event__pb2.AllocateTransferRequest.FromString,
                    response_serializer=proto_dot_allocation__pb2.Allocation.SerializeToString,
            ),
            'BatchInsertTransfers': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchInsertTransfers,
                    request_deserializer=proto_dot_fin__event__pb2.BatchInsertTransfersRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTransfer,
                    request_deserializer=proto_dot_transfer__pb2.Transfer.FromString,
                    response_serializer=proto_dot_transfer__pb2.Transfer.SerializeToString,
            ),
            'AggregateTransfers': grpc.unary_unary_rpc_method_handler(
                    servicer.AggregateTransfers,
                    request_deserializer=proto_dot_requests__pb2.AggregateRequest.FromString,
                    response_serializer=proto_dot_event__aggregate__pb2.EventAggregate.SerializeToString,
            ),
            'ListAccruals': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccruals,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_fin__event__pb2.ListAccrualsResponse.SerializeToString,
            ),
            'GetAccrual': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccrual,
                    request_deserializer=proto_dot_requests__pb2.GetRequest.FromString,
                    response_serializer=proto_dot_accrual__pb2.Accrual.SerializeToString,
            ),
            'CreateAccrual': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccrual,
                    request_deserializer=proto_dot_accrual__pb2.Accrual.FromString,
                    response_serializer=proto_dot_accrual__pb2.Accrual.SerializeToString,
            ),
            'UpdateAccrual': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAccrual,
                    request_deserializer=proto_dot_accrual__pb2.Accrual.FromString,
                    response_serializer=proto_dot_accrual__pb2.Accrual.SerializeToString,
            ),
            'AggregateAccruals': grpc.unary_unary_rpc_method_handler(
                    servicer.AggregateAccruals,
                    request_deserializer=proto_dot_requests__pb2.AggregateRequest.FromString,
                    response_serializer=proto_dot_accruals__aggregate__pb2.AccrualsAggregate.SerializeToString,
            ),
            'BatchInsertAccruals': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchInsertAccruals,
                    request_deserializer=proto_dot_fin__event__pb2.BatchInsertAccrualsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GenerateAccrualPDF': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAccrualPDF,
                    request_deserializer=proto_dot_requests__pb2.GetRequest.FromString,
                    response_serializer=proto_dot_fin__event__pb2.FileResponse.SerializeToString,
            ),
            'ListProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProducts,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_fin__event__pb2.ListProductsResponse.SerializeToString,
            ),
            'ListPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPositions,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_fin__event__pb2.ListPositionsResponse.SerializeToString,
            ),
            'UpdatePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePosition,
                    request_deserializer=proto_dot_position__pb2.Position.FromString,
                    response_serializer=proto_dot_position__pb2.Position.SerializeToString,
            ),
            'BatchInsertPostions': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchInsertPostions,
                    request_deserializer=proto_dot_fin__event__pb2.BatchInsertPositionsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListArticles,
                    request_deserializer=proto_dot_fin__event__pb2.ListArticlesRequest.FromString,
                    response_serializer=proto_dot_fin__event__pb2.ListArticlesResponse.SerializeToString,
            ),
            'GetArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArticle,
                    request_deserializer=proto_dot_requests__pb2.GetRequest.FromString,
                    response_serializer=proto_dot_article__pb2.Article.SerializeToString,
            ),
            'CreateArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateArticle,
                    request_deserializer=proto_dot_article__pb2.Article.FromString,
                    response_serializer=proto_dot_article__pb2.Article.SerializeToString,
            ),
            'UpdateArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateArticle,
                    request_deserializer=proto_dot_article__pb2.Article.FromString,
                    response_serializer=proto_dot_article__pb2.Article.SerializeToString,
            ),
            'DeleteArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteArticle,
                    request_deserializer=proto_dot_requests__pb2.DeleteRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListAllocations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllocations,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_fin__event__pb2.ListAllocationsResponse.SerializeToString,
            ),
            'CreateAllocation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAllocation,
                    request_deserializer=proto_dot_allocation__pb2.Allocation.FromString,
                    response_serializer=proto_dot_allocation__pb2.Allocation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FinEvent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FinEvent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FinEvent(object):
    """Репы - Трансферы, Перевод, Продукт
    """

    @staticmethod
    def ListSignatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/ListSignatures',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_fin__event__pb2.ListSignaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/ListComments',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_fin__event__pb2.ListCommentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/CreateComment',
            proto_dot_comment__pb2.Comment.SerializeToString,
            proto_dot_comment__pb2.Comment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/UpdateComment',
            proto_dot_comment__pb2.Comment.SerializeToString,
            proto_dot_comment__pb2.Comment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/DeleteComment',
            proto_dot_requests__pb2.DeleteRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/CreatePermission',
            proto_dot_permission__pb2.Permission.SerializeToString,
            proto_dot_permission__pb2.Permission.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/ListPermissions',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_fin__event__pb2.ListPermissionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/DeletePermission',
            proto_dot_requests__pb2.DeleteRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/ListActions',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_fin__event__pb2.ListActionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTransfers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/ListTransfers',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_fin__event__pb2.ListTransfersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/GetTransfer',
            proto_dot_requests__pb2.GetRequest.SerializeToString,
            proto_dot_transfer__pb2.Transfer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/CreateTransfer',
            proto_dot_transfer__pb2.Transfer.SerializeToString,
            proto_dot_transfer__pb2.Transfer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllocateTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/AllocateTransfer',
            proto_dot_fin__event__pb2.AllocateTransferRequest.SerializeToString,
            proto_dot_allocation__pb2.Allocation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInsertTransfers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/BatchInsertTransfers',
            proto_dot_fin__event__pb2.BatchInsertTransfersRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/UpdateTransfer',
            proto_dot_transfer__pb2.Transfer.SerializeToString,
            proto_dot_transfer__pb2.Transfer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AggregateTransfers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/AggregateTransfers',
            proto_dot_requests__pb2.AggregateRequest.SerializeToString,
            proto_dot_event__aggregate__pb2.EventAggregate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAccruals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/ListAccruals',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_fin__event__pb2.ListAccrualsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccrual(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/GetAccrual',
            proto_dot_requests__pb2.GetRequest.SerializeToString,
            proto_dot_accrual__pb2.Accrual.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAccrual(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/CreateAccrual',
            proto_dot_accrual__pb2.Accrual.SerializeToString,
            proto_dot_accrual__pb2.Accrual.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAccrual(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/UpdateAccrual',
            proto_dot_accrual__pb2.Accrual.SerializeToString,
            proto_dot_accrual__pb2.Accrual.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AggregateAccruals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/AggregateAccruals',
            proto_dot_requests__pb2.AggregateRequest.SerializeToString,
            proto_dot_accruals__aggregate__pb2.AccrualsAggregate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInsertAccruals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/BatchInsertAccruals',
            proto_dot_fin__event__pb2.BatchInsertAccrualsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateAccrualPDF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/GenerateAccrualPDF',
            proto_dot_requests__pb2.GetRequest.SerializeToString,
            proto_dot_fin__event__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/ListProducts',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_fin__event__pb2.ListProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/ListPositions',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_fin__event__pb2.ListPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/UpdatePosition',
            proto_dot_position__pb2.Position.SerializeToString,
            proto_dot_position__pb2.Position.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInsertPostions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/BatchInsertPostions',
            proto_dot_fin__event__pb2.BatchInsertPositionsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/ListArticles',
            proto_dot_fin__event__pb2.ListArticlesRequest.SerializeToString,
            proto_dot_fin__event__pb2.ListArticlesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/GetArticle',
            proto_dot_requests__pb2.GetRequest.SerializeToString,
            proto_dot_article__pb2.Article.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/CreateArticle',
            proto_dot_article__pb2.Article.SerializeToString,
            proto_dot_article__pb2.Article.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/UpdateArticle',
            proto_dot_article__pb2.Article.SerializeToString,
            proto_dot_article__pb2.Article.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/DeleteArticle',
            proto_dot_requests__pb2.DeleteRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/ListAllocations',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_fin__event__pb2.ListAllocationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAllocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinEvent/CreateAllocation',
            proto_dot_allocation__pb2.Allocation.SerializeToString,
            proto_dot_allocation__pb2.Allocation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
