# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/operation_type.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/operation_type.proto*|\n\rOperationType\x12\x1a\n\x16OPERATION_TYPE_UNKNOWN\x10\x00\x12\x19\n\x15OPERATION_TYPE_INSERT\x10\x01\x12\x19\n\x15OPERATION_TYPE_UPDATE\x10\x02\x12\x19\n\x15OPERATION_TYPE_DELETE\x10\x03\x42&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.operation_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_OPERATIONTYPE']._serialized_start=30
  _globals['_OPERATIONTYPE']._serialized_end=154
# @@protoc_insertion_point(module_scope)
