# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/operation_accruals.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dictum_proto.proto import operation_pb2 as proto_dot_operation__pb2
from dictum_proto.proto import accrual_allocations_pb2 as proto_dot_accrual__allocations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eproto/operation_accruals.proto\x1a\x15proto/operation.proto\x1a\x1fproto/accrual_allocations.proto\"Y\n\x11OperationAccruals\x12\x1d\n\toperation\x18\x01 \x01(\x0b\x32\n.Operation\x12%\n\x08\x61\x63\x63ruals\x18\x02 \x03(\x0b\x32\x13.AccrualAllocationsB&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.operation_accruals_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_OPERATIONACCRUALS']._serialized_start=90
  _globals['_OPERATIONACCRUALS']._serialized_end=179
# @@protoc_insertion_point(module_scope)
