# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/position.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dictum_proto.proto import product_pb2 as proto_dot_product__pb2
from dictum_proto.proto import accrual_pb2 as proto_dot_accrual__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/position.proto\x1a\x13proto/product.proto\x1a\x13proto/accrual.proto\"\xc0\x01\n\x08Position\x12\x13\n\x0bposition_id\x18\x01 \x01(\x05\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\x12\x12\n\nproduct_id\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x10\n\x08quantity\x18\x05 \x01(\x05\x12\x0b\n\x03sum\x18\x06 \x01(\x01\x12\x15\n\rresource_name\x18\x07 \x01(\t\x12\x19\n\x07product\x18\t \x01(\x0b\x32\x08.Product\x12\x19\n\x07\x61\x63\x63rual\x18\x0c \x01(\x0b\x32\x08.AccrualB&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.position_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_POSITION']._serialized_start=67
  _globals['_POSITION']._serialized_end=259
# @@protoc_insertion_point(module_scope)
