# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/role.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/role.proto*\x8c\x01\n\x04Role\x12\x10\n\x0cROLE_UNKNOWN\x10\x00\x12\x0e\n\nROLE_OWNER\x10\x01\x12\x12\n\x0eROLE_TREASURER\x10\x02\x12\x13\n\x0fROLE_ACCOUNTANT\x10\x03\x12\x0f\n\x0bROLE_VIEWER\x10\x04\x12\x0f\n\x0bROLE_PLUGIN\x10\x05\x12\x17\n\x13ROLE_AUTHENTICATION\x10\x06\x42&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.role_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_ROLE']._serialized_start=21
  _globals['_ROLE']._serialized_end=161
# @@protoc_insertion_point(module_scope)
