# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/service_run.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from dictum_proto.proto import service_run_state_pb2 as proto_dot_service__run__state__pb2
from dictum_proto.proto import service_pb2 as proto_dot_service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/service_run.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dproto/service_run_state.proto\x1a\x13proto/service.proto\"\x9c\x01\n\nServiceRun\x12\x12\n\nservice_id\x18\x01 \x01(\x05\x12\x1f\n\x05state\x18\x03 \x01(\x0e\x32\x10.ServiceRunState\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x19\n\x07service\x18\x06 \x01(\x0b\x32\x08.Service\x12-\n\tsync_time\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampB&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.service_run_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_SERVICERUN']._serialized_start=113
  _globals['_SERVICERUN']._serialized_end=269
# @@protoc_insertion_point(module_scope)
