# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/telegram_user_chat.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import telegram_user_pb2 as proto_dot_telegram__user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eproto/telegram_user_chat.proto\x1a\x19proto/telegram_user.proto\"\x8a\x01\n\x10TelegramUserChat\x12\x1d\n\x15telegram_user_chat_id\x18\x01 \x01(\x05\x12\x17\n\x0f\x63hat_source_key\x18\x02 \x01(\x05\x12\x18\n\x10telegram_user_id\x18\x03 \x01(\x05\x12$\n\rtelegram_user\x18\x04 \x01(\x0b\x32\r.TelegramUserB&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.telegram_user_chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_TELEGRAMUSERCHAT']._serialized_start=62
  _globals['_TELEGRAMUSERCHAT']._serialized_end=200
# @@protoc_insertion_point(module_scope)
