# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/transfer_type.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/transfer_type.proto*\xca\x01\n\x0cTransferType\x12\x19\n\x15TRANSFER_TYPE_UNKNOWN\x10\x00\x12\x19\n\x15TRANSFER_TYPE_PAYMENT\x10\x01\x12 \n\x1cTRANSFER_TYPE_INITIALIZATION\x10\x02\x12*\n&TRANSFER_TYPE_TRANSFER_WITH_CONVERSION\x10\x03\x12\x18\n\x14TRANSFER_TYPE_MOVING\x10\x04\x12\x1c\n\x18TRANSFER_TYPE_COMMISSION\x10\x05\x42&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.transfer_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_TRANSFERTYPE']._serialized_start=30
  _globals['_TRANSFERTYPE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
