# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/transfers_aggregate.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto/transfers_aggregate.proto\"\x8c\x01\n\x12TransfersAggregate\x12\r\n\x05total\x18\x01 \x01(\x01\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x14\n\x0cincome_total\x18\x03 \x01(\x01\x12\x14\n\x0cincome_count\x18\x04 \x01(\x05\x12\x15\n\routcome_total\x18\x05 \x01(\x01\x12\x15\n\routcome_count\x18\x06 \x01(\x05\x42&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.transfers_aggregate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_TRANSFERSAGGREGATE']._serialized_start=36
  _globals['_TRANSFERSAGGREGATE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
