# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import auth_provider_pb2 as proto_dot_auth__provider__pb2
from proto import requests_pb2 as proto_dot_requests__pb2
from proto import user_hub_pb2 as proto_dot_user__hub__pb2
from proto import user_pb2 as proto_dot_user__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/user_hub_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class UserHubStub(object):
    """Репо - User
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUsers = channel.unary_unary(
                '/UserHub/ListUsers',
                request_serializer=proto_dot_requests__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_user__hub__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/UserHub/GetUser',
                request_serializer=proto_dot_requests__pb2.GetRequest.SerializeToString,
                response_deserializer=proto_dot_user__pb2.User.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/UserHub/CreateUser',
                request_serializer=proto_dot_user__pb2.User.SerializeToString,
                response_deserializer=proto_dot_user__pb2.User.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/UserHub/UpdateUser',
                request_serializer=proto_dot_user__pb2.User.SerializeToString,
                response_deserializer=proto_dot_user__pb2.User.FromString,
                _registered_method=True)
        self.CreateUserProvider = channel.unary_unary(
                '/UserHub/CreateUserProvider',
                request_serializer=proto_dot_auth__provider__pb2.AuthProvider.SerializeToString,
                response_deserializer=proto_dot_auth__provider__pb2.AuthProvider.FromString,
                _registered_method=True)


class UserHubServicer(object):
    """Репо - User
    """

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUserProvider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserHubServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=proto_dot_requests__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_user__hub__pb2.ListUsersResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=proto_dot_requests__pb2.GetRequest.FromString,
                    response_serializer=proto_dot_user__pb2.User.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=proto_dot_user__pb2.User.FromString,
                    response_serializer=proto_dot_user__pb2.User.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=proto_dot_user__pb2.User.FromString,
                    response_serializer=proto_dot_user__pb2.User.SerializeToString,
            ),
            'CreateUserProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUserProvider,
                    request_deserializer=proto_dot_auth__provider__pb2.AuthProvider.FromString,
                    response_serializer=proto_dot_auth__provider__pb2.AuthProvider.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserHub', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UserHub', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserHub(object):
    """Репо - User
    """

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserHub/ListUsers',
            proto_dot_requests__pb2.ListRequest.SerializeToString,
            proto_dot_user__hub__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserHub/GetUser',
            proto_dot_requests__pb2.GetRequest.SerializeToString,
            proto_dot_user__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserHub/CreateUser',
            proto_dot_user__pb2.User.SerializeToString,
            proto_dot_user__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserHub/UpdateUser',
            proto_dot_user__pb2.User.SerializeToString,
            proto_dot_user__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUserProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserHub/CreateUserProvider',
            proto_dot_auth__provider__pb2.AuthProvider.SerializeToString,
            proto_dot_auth__provider__pb2.AuthProvider.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
