# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from proto import employee_pb2 as proto_dot_employee__pb2
from proto import telegram_user_pb2 as proto_dot_telegram__user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/user.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14proto/employee.proto\x1a\x19proto/telegram_user.proto\"\x83\x02\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tuser_name\x18\x03 \x01(\t\x12\x11\n\tfull_name\x18\x05 \x01(\t\x12\x18\n\x10telegram_user_id\x18\x07 \x01(\x05\x12\x0f\n\x07ref_key\x18\t \x01(\t\x12\x1c\n\temployees\x18\x0f \x03(\x0b\x32\t.Employee\x12\x15\n\rresource_name\x18\x0b \x01(\t\x12$\n\rtelegram_user\x18\x10 \x01(\x0b\x32\r.TelegramUser\x12/\n\x0b\x63reate_time\x18\x11 \x01(\x0b\x32\x1a.google.protobuf.TimestampB&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _globals['_USER']._serialized_start=103
  _globals['_USER']._serialized_end=362
# @@protoc_insertion_point(module_scope)
